package mastgrpc

import (
	"context"
	"errors"
	"log"
	"reflect"

	middleware "github.com/grpc-ecosystem/go-grpc-middleware"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
)

func (b *GRPCBuilder) Dial() (*grpc.ClientConn, error) {
	return b.dialContext(context.Background())
}

// Dial return a ClientConn by DialOption
// then you need use pb.New[ServiceName]Client(yourClientConn)
// to Create client which could Call Service and use context
// Should： ClientConn should be closed by Close()
func (b *GRPCBuilder) dialContext(context context.Context) (*grpc.ClientConn, error) {
	b.dopts = append(b.dopts, grpc.WithInsecure())
	if len(b.unaryServerInterceptors) != 0 {
		b.dopts = append(b.dopts, grpc.WithUnaryInterceptor(middleware.ChainUnaryClient(b.unaryClientInterceptors...)))
	}

	if len(b.streamServerInterceptors) != 0 {
		b.dopts = append(b.dopts, grpc.WithStreamInterceptor(middleware.ChainStreamClient(b.streamClientInterceptors...)))
	}

	return grpc.DialContext(context, b.Addr, b.dopts...)
}

// DialTLS creates a client connection over tls transport with given serverCert and server's name.
func (b *GRPCBuilder) DialTLS(ctx context.Context, file string, name string) (conn *grpc.ClientConn, err error) {
	var creds credentials.TransportCredentials
	creds, err = credentials.NewClientTLSFromFile(file, name)
	if err != nil {
		return
	}
	b.dopts = append(b.dopts, grpc.WithTransportCredentials(creds))
	return b.dialContext(ctx)
}

// Client to call Service
type Client struct {
	c interface{} // it's PB file's involve Client to call method
	context.Context
}

// CallUnary
// [3]reflect.Value in[0] is context.Context, in[1] is your message type which generated by pb file.
// in[2] is grpc.CallOption
func (c *Client) CallUnary(methodName string, in []reflect.Value) (interface{}, error) {
	m, ok := reflect.TypeOf(c.c).MethodByName(methodName)
	if !ok {
		log.Fatal("method not found")
	}

	if len(in) != 3 {
		return nil, errors.New("mistake argument")
	}
	out := m.Func.Call(in)

	if len(out) != 2 {
		return nil, errors.New("mistake method")
	}

	return out[0].Interface(), out[1].Interface().(error)
}

// callStream
// [3]reflect.Value in[0] is context.Context, in[1] is your message type which generated by pb file.
// in[2] is grpc.CallOption
func (c *Client) callStream(methodName string, in []reflect.Value) (interface{}, error) {
	m, ok := reflect.TypeOf(c.c).MethodByName(methodName)
	if !ok {
		log.Fatal("method not found")
	}

	out := m.Func.Call(in)

	return out[0].Interface(), out[1].Interface().(error)
}
